### ISSUE TITLE
Start implementing integro-interpolation method

### ISSUE THREAD

**Issue by zoeself** [fedorpashin/physics#8]
The puzzle ``601573080`` originating from #4 has to be resolved:

https://github.com/fedorpashin/physics/blob/e085acd013d799a4febbc47a3baaf071094dff8e/physics/equations/heat/integro_interpolation_method.py#L14-L14

"Implement integro-interpolation method".

The puzzle was created by Fedor Pashin at ``2021-09-18 22:37:37 +0300``. 
Estimation is ``240 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by zoeself** [comment]
@fedorpashin this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-09-29T11:05:05.654643``.

Estimation here is ``240 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@fedorpashin Don't forget to close this ticket before the deadline (2021-09-29T11:05:06). You are past the first half of the allowed period.

**Comment by fedorpashin** [comment]
@zoeself deregister

**Comment by zoeself** [comment]
> @zoeself deregister

@fedorpashin ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by fedorpashin** [comment]
@zoeself register

**Comment by zoeself** [comment]
> @zoeself register

@fedorpashin I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by zoeself** [comment]
@fedorpashin this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-10-05T16:15:04.063357``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@fedorpashin thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
